- package.json
- src/app/components/NotFoundPage/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/NotFoundPage/__tests__/index.test.tsx
- src/app/containers/HomePage/__tests__/__snapshots__/index.test.tsx.snap
- src/app/containers/HomePage/__tests__/index.test.tsx
- src/app/containers/HomePage/index.tsx
- src/index.tsx
- src/setupProxy.js
- src/utils/__test__/api.test.tsx
- src/utils/api.ts
- yarn.lock
> feat(api): add contract manager api and proxy

- package.json
- src/styles/media.ts
- yarn.lock
> feat: add useBreakpoint

- package.json
- src/styles/__tests__/media.test.ts
- src/styles/media.ts
- yarn.lock
> fix(media): old media query don't support ts well

- src/styles/__tests__/createBreakpoint.test.tsx
- src/styles/createBreakpoint.ts
- src/styles/media.ts
> fix: createBreakpoint use max-width logic

- src/utils/api.ts
> fix(api): pass ref of params to useSWR

- package.json
- public/font.css
- public/index.html
- src/app/components/TablePanel/index.tsx
- src/app/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/Tabs/index.tsx
- src/app/components/TabsTablePanel/Label.tsx
- src/app/components/Text/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/Text/index.tsx
- src/app/index.tsx
- src/styles/global-styles.ts
- yarn.lock
https://scotch.io/@micwanyoike/how-to-add-fonts-to-a-react-project
> feat: add font url CU-4hmpk1, use webfontloader

- src/app/components/PageHeader/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/PageHeader/index.tsx
- src/app/components/TablePanel/Panel.tsx
- src/app/components/TabsTablePanel/Label.tsx
- src/app/components/Text/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/Text/index.tsx
- src/app/containers/Header/Search/Logo.tsx
- src/app/containers/Header/Search/__tests__/__snapshots__/index.test.tsx.snap
- src/app/containers/Header/Search/index.tsx
- src/app/containers/Header/__tests__/__snapshots__/index.test.tsx.snap
- src/app/containers/Tokens/index.tsx
- src/styles/global-styles.ts
1. 主题蓝Ctheme-5#0054FE>Scan blue#1E3DE4 
2. 主体标题 #0F1327>Brand black#1A1A1A 
3. 主体文字信息#20253A>Gray 80# 333333
> feat(theme): update theme color with new design

- src/app/components/TablePanel/Panel.tsx
- src/app/containers/BlocksAndTransactions/index.tsx
- src/app/containers/Header/__tests__/__snapshots__/index.test.tsx.snap
- src/app/containers/Header/index.tsx
- src/app/containers/Tokens/index.tsx
- src/app/index.tsx
1. in Main wrapper, add max-width, replace margin-top width padding-top
2. remove page wrapper config of Block&Txn and tokens page
3. modify display string issue of Header
4. add Card wrapper to TablePanel
> feat(layout): update Main wrapper

- src/app/__tests__/__snapshots__/index.test.tsx.snap
- src/app/containers/Header/HeaderLink.tsx
- src/app/containers/Header/__tests__/__snapshots__/index.test.tsx.snap
- src/app/containers/Header/__tests__/index.test.tsx
- src/app/containers/Header/index.tsx
- src/setupTests.ts
> fix: header link, home logo link, header end menu select style

- src/app/containers/Header/__tests__/__snapshots__/index.test.tsx.snap
- src/app/containers/Header/index.tsx
> fix(Header): header padding CU-4tuqzr

- src/app/containers/Header/HeaderLink.tsx
- src/app/containers/Header/__tests__/__snapshots__/index.test.tsx.snap
- src/app/containers/Header/index.tsx
- src/locales/i18n.ts
> fix(HeaderLink): language select style CU-4quw26

- src/app/components/TabsTablePanel/Panel.tsx
- src/app/containers/AddressContractDetail/Table.tsx
- src/app/containers/Blocks/BottomTablePanel.tsx
> fix(AddressDetailPage): hide mined block tab if it's 0

- .gitignore
- Jenkinsfile
- src/app/containers/BlocksAndTransactions/Dag/Dag.tsx
- src/app/containers/BlocksAndTransactions/Dag/index.tsx
- src/app/containers/BlocksAndTransactions/Loadable.tsx
- src/app/containers/BlocksAndTransactions/index.tsx
- src/utils/api.ts
> feat(Dag): add Dag CU-4tr1ha

- src/app/components/TablePanel/Panel.tsx
- src/app/containers/Transaction/index.tsx
- src/utils/index.ts
1. fix: update table th color of TablePanel component
2. feat: update formatNumber util fn
3. fix: transaction timestamp format and style issue
> feat: fix clickup

- src/app/containers/AddressContractDetail/Table.tsx
- src/app/containers/Header/HeaderLink.tsx
- src/app/containers/Header/__tests__/__snapshots__/index.test.tsx.snap
CU-4vv9nh
CU-4vv9yr
CU-4vva18
CU-4vv9zz
---
#
> fix: fix several bug

- src/app/containers/AddressContractDetail/TokenBalanceSelect.tsx
- src/locales/zh_cn/translation.json
> fix: bug fixes

- src/app/components/Link/index.tsx
- src/app/components/SkeletonContainer/index.tsx
- src/app/components/TabsTablePanel/useTableData.ts
- src/app/containers/AddressContractDetail/AddressInfoCards.tsx
- src/app/containers/AddressContractDetail/ContractMetadata.tsx
- src/app/containers/AddressContractDetail/Table.tsx
- src/app/containers/AddressContractDetail/TokenBalanceSelect.tsx
- src/app/containers/AddressContractDetail/__tests__/__snapshots__/AddressDetailPage.test.tsx.snap
- src/app/containers/AddressContractDetail/__tests__/__snapshots__/ContractDetailPage.test.tsx.snap
- src/app/containers/AddressContractDetail/layouts.ts
- src/app/containers/TokenDetail/Transfers.tsx
- src/utils/api.ts
- src/utils/tableColumns/token.tsx
1. fix: add Skeleton to contract detail page
2. fix: from&to row without link if the value same as current route address
3. fix: support metakey control of Link component
> fix: fixed bugs

- src/app/containers/AddressContractDetail/ContractMetadata.tsx
- src/app/containers/Header/HeaderLink.tsx
- src/utils/index.ts
> fix(ContractMetadata): always display edit

- src/app/containers/Header/__tests__/__snapshots__/index.test.tsx.snap
- src/app/containers/Header/index.tsx
> feat: headerlink hover bg CU-4quwc8

- src/app/containers/BlocksAndTransactions/Dag/Dag.tsx
- src/locales/en/translation.json
> fix: contract admin wording

- now.json
- src/setupProxy.js
- src/utils/api.ts
- src/utils/httpRequest.ts
- src/utils/index.ts
> fix: /api to /v1

- src/locales/en/translation.json
> fix: contract admin wording CU-4tvh9v

- src/app/containers/HomePage/Notice.tsx
- src/utils/api.ts
> fix: new useClientVersion use only /rpc

- src/app/containers/TokenDetail/index.tsx
> fix: icon size

- src/app/containers/Block/DescriptionPanel.tsx
> fix: fix bugs

- src/utils/cfx.ts
- src/utils/hooks/useTestnet.ts
> fix(sponsor): remove hook on util

- src/app/containers/HomePage/Notice.tsx
> fix(i18n): fix the issue for i18n of notice

- src/app/containers/AddressContractDetail/AddressContractDetailPage.tsx
- src/app/containers/AddressContractDetail/ContractDetailPage.tsx
- src/app/containers/AddressContractDetail/__tests__/__snapshots__/ContractDetailPage.test.tsx.snap
- src/app/containers/Header/Search/index.tsx
- src/utils/index.ts
> feat: inner contract detail(CU-55xpbu)

- src/app/containers/BlocksAndTransactions/Dag/lib-dag.js
> fix: Dag console

- src/app/containers/BlocksAndTransactions/index.tsx
> feat: mobile not display dag

- package.json
- src/utils/cfx.ts
- src/utils/httpRequest.ts
- yarn.lock
> fix: upgrade version of js-conflux-sdk

- src/app/containers/Sponsor/index.tsx
> fix: new error for faucet

- public/index.html
- src/app/containers/AddressContractDetail/DatePickerWithQuery.tsx
> fix: CU-5bqhnr, hide datepicker when click away

- src/app/components/Contract/index.tsx
> style(Contract): Contract Creation, inputStyle margin

- package.json
- src/app/components/Contract/index.tsx
- src/app/containers/AddressContractDetail/ActionButton.tsx
- src/app/containers/AddressContractDetail/PickerWithQuery.tsx
- src/app/containers/AddressContractDetail/Table.tsx
- src/styles/global-styles.ts
- src/utils/cfx.ts
- yarn.lock
> feat: Feature 2.0.2

- src/app/components/TabsTablePanel/useTabTableData.ts
- src/app/components/TabsTablePanel/useTableData.ts
* fix: CU-57xxcf, update with lastest notice (#185)
* fix: CU-5du9wh, fetch of none table tab issue
Co-authored-by: Angelia <greenfish84@126.com>
> fix: CU-5du9wh, fetch of none table tab issue (#195)

- src/app/containers/HomePage/Notice.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
> feat: SCAN-10, update testnet notice

- src/app/components/TabsTablePanel/useTabTableData.ts
- src/app/components/TabsTablePanel/useTableData.ts
- src/app/containers/HomePage/Notice.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
> feat: update testnet notice

- package.json
- src/app/containers/Sponsor/index.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
- src/utils/cfx.ts
- yarn.lock
> feat: sponsor feature on feature-2.0.3

- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
> feat: update notice

- src/app/components/Contract/index.tsx
> style(contract): contract creation - the location of input sursor

- src/app/containers/Header/Search/__tests__/__snapshots__/index.test.tsx.snap
- src/app/containers/Header/Search/index.tsx
- src/app/containers/Header/__tests__/__snapshots__/index.test.tsx.snap
> fix(header): bug fix when < 1200px

- package.json
- src/utils/index.ts
- yarn.lock
> feat: update react-ui version

- src/utils/cfx.ts
> feat: modify faucet address of mainnet

- src/app/containers/AddressContractDetail/Table.tsx
> fix: from address

- src/app/containers/AddressContractDetail/Table.tsx
> fix: to address display

- src/app/components/Chart/Chart.jsx
- src/app/components/Chart/draw.js
- src/app/components/Chart/usePlot.js
> fix: format date and time

- src/app/components/Chart/Chart.jsx
- src/app/components/Chart/draw.js
- src/app/components/Chart/usePlot.js
> feat(chart): add format

- src/app/components/Chart/draw.js
- src/app/components/Chart/usePlot.js
> fix(chart): split xAxis text into two rows

- src/app/containers/AddressContractDetail/TokenBalanceSelect.tsx
- src/utils/api.ts
> fix: SCAN-185, add high decimals tooltip to address token select list

- src/app/containers/AddressContractDetail/ContractMetadata.tsx
- src/app/containers/AddressContractDetail/Table.tsx
- src/setupProxy.js
- src/utils/tableColumns/token.tsx
> feat: SCAN-285 optimize transfer list token without name/symbol

- src/index.tsx
- src/setupProxy.js
- src/utils/request.ts
> feat: add console logo, network and version show

- src/app/containers/TokenDetail/index.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
- src/utils/request.ts
> feat: SCAN-310, update request error handler for latest error codes

- src/app/components/ContractAbi/Func.tsx
- src/app/components/ContractAbi/FuncList.tsx
- src/app/components/ContractAbi/OutputItem.tsx
- src/app/containers/AddressContractDetail/Table.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
> fix: several bus

- package.json
- src/app/components/ContractAbi/Func.tsx
- src/utils/index.ts
- yarn.lock
> fix: several bugs

- src/app/components/ContractAbi/FuncList.tsx
> feat: hide the reset button

- src/app/components/ContractAbi/OutputItem.tsx
> fix: catch the error for the unknown type

- package.json
- src/app/__tests__/__snapshots__/index.test.tsx.snap
- src/app/containers/AddressConverter/List.tsx
- src/app/containers/AddressConverter/Loadable.tsx
- src/app/containers/AddressConverter/__tests__/__snapshots__/index.test.tsx.snap
- src/app/containers/AddressConverter/__tests__/index.test.tsx
- src/app/containers/AddressConverter/index.tsx
- src/app/containers/Footer/index.tsx
- src/app/index.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
- src/utils/cfx.ts
- yarn.lock
> feat: add address converter page

- package.json
- src/app/components/CopyButton/index.tsx
- src/app/containers/AddressContractDetail/__tests__/__snapshots__/AddressDetailPage.test.tsx.snap
- src/app/containers/AddressContractDetail/__tests__/__snapshots__/ContractDetailPage.test.tsx.snap
- src/app/containers/AddressConverter/List.tsx
- src/app/containers/AddressConverter/__tests__/__snapshots__/index.test.tsx.snap
- src/app/containers/AddressConverter/index.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
- yarn.lock
> feat: add custom network id in address converter

- src/app/containers/AddressConverter/__tests__/__snapshots__/index.test.tsx.snap
- src/app/containers/AddressConverter/index.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
> feat: update remark

- semantic.yml
- src/app/containers/AddressConverter/__tests__/__snapshots__/index.test.tsx.snap
- src/app/containers/AddressConverter/index.tsx
- src/app/containers/Header/__tests__/__snapshots__/index.test.tsx.snap
- src/app/containers/Header/index.tsx
- src/app/containers/TokenDetail/Basic.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
> feat: update address converter

- src/app/components/Contract/index.tsx
- src/app/components/DappButton/index.tsx
- src/app/containers/AddressContractDetail/ContractDetailPage.tsx
- src/app/containers/AddressContractDetail/__tests__/__snapshots__/ContractDetailPage.test.tsx.snap
- src/app/containers/Sponsor/index.tsx
- src/app/containers/Tokens/index.tsx
- src/app/containers/Transaction/index.tsx
- src/utils/cfx.ts
- src/utils/tableColumns/token.tsx
> fix: some cip-37 bug

- src/app/components/AddressContainer/index.tsx
- src/app/containers/BlocksAndTransactions/index.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
- src/utils/cfx.ts
- src/utils/index.ts
> feat: add address icon hover text and support invalid conflux address & fix some style problems

- src/app/components/DappButton/index.tsx
- src/app/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/Tabs/index.tsx
- src/app/components/TabsTablePanel/Panel.tsx
- src/app/containers/AddressContractDetail/AddressDetailPage.tsx
- src/app/containers/AddressContractDetail/AddressInfoCards.tsx
- src/app/containers/AddressContractDetail/ContractDetailPage.tsx
- src/app/containers/AddressContractDetail/ContractMetadata.tsx
- src/app/containers/AddressContractDetail/Table.tsx
- src/app/containers/Block/DescriptionPanel.tsx
- src/app/containers/Sponsor/index.tsx
- src/app/containers/Transaction/index.tsx
- src/utils/cfx.ts
> feat: optimize address detail page presentation and fix some bug

- .gitignore
- src/app/components/AddressContainer/index.tsx
- src/app/components/List/index.tsx
- src/app/components/TablePanel/Panel.tsx
- src/app/components/Tabs/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/Tabs/index.tsx
- src/app/containers/AddressContractDetail/Table.tsx
- src/app/containers/AddressContractDetail/TokenBalanceSelect.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
> feat: mobile style fix

- src/app/containers/AddressContractDetail/ContractMetadata.tsx
- src/app/containers/TokenDetail/Basic.tsx
- src/locales/en/translation.json
- src/utils/index.ts
- src/utils/tableColumns/token.tsx
> fix: some style problems

- public/index.html
- src/app/containers/AddressContractDetail/ContractMetadata.tsx
- src/app/containers/Sponsor/index.tsx
- src/app/containers/TokenDetail/Basic.tsx
- src/app/containers/Transaction/index.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
- src/utils/index.ts
- src/utils/sponsorFaucet/faucet.js
> feat: add google analysis and update sponsor faucet

- src/app/components/AddressContainer/index.tsx
- src/app/containers/Tokens/index.tsx
- src/utils/tableColumns/token.tsx
> fix: hotfix txns direction error

- src/app/components/AddressContainer/index.tsx
- src/app/containers/Tokens/index.tsx
- src/utils/api.ts
- src/utils/tableColumns/token.tsx
> fix: transfer list token info match error

- src/utils/cfx.ts
> fix: modify to mainnet contractManagerAddress

- src/app/components/StatsCard/index.tsx
- src/app/containers/Accounts/index.tsx
- src/app/containers/AddressContractDetail/AddressMetadata.tsx
- src/app/containers/Statistics/index.tsx
- src/app/index.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
- src/utils/index.ts
- src/utils/tableColumns/account.tsx
- src/utils/tableColumns/index.ts
- src/utils/tableColumns/utils.tsx
> feat: statistics use monospace font

- src/app/containers/AddressContractDetail/ContractDetailPage.tsx
> feat: contract detail add staking info

- src/app/__tests__/__snapshots__/index.test.tsx.snap
- src/app/containers/HomePage/index.tsx
- src/app/index.tsx
> fix: SCAN-500, add router block&txn redirect for compatible

- src/app/components/TabsTablePanel/useTableData.ts
> fix: hotfix SCAN-504, update Pagination total page count issue

- .circleci/config.yml
> chore: change circleci timeout

- src/app/components/ConnectWallet/Modal.tsx
- src/app/components/ConnectWallet/index.tsx
- src/app/components/ContractAbi/Func.tsx
> feat: SCAN-544, add wallet connect button to write&read contract page

- src/app/containers/Footer/index.tsx
- src/app/containers/Tokens/index.tsx
- src/utils/tableColumns/token.tsx
- src/utils/tableColumns/utils.tsx
> feat: SCAN-574, update erc token table

- src/app/components/AddressContainer/index.tsx
- src/app/components/ContractAbi/FuncList.tsx
- src/app/components/TablePanel/Panel.tsx
- src/app/containers/AddressContractDetail/ContractMetadata.tsx
- src/app/containers/BlocknumberCalc/Countdown.tsx
- src/app/containers/BlocknumberCalc/index.tsx
- src/app/containers/TokenDetail/Transfers.tsx
- src/app/containers/TokenDetail/index.tsx
- src/app/containers/Tokens/index.tsx
- src/utils/index.ts
- src/utils/tableColumns/token.tsx
> fix: 2.1.2 bugs

- src/app/containers/AddressContractDetail/AddressMetadata.tsx
- src/app/containers/TokenDetail/Transfers.tsx
- src/app/containers/TokenDetail/index.tsx
- src/utils/api.ts
- src/utils/tableColumns/token.tsx
> feat: token holders list

- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
> feat: SCAN-599 remove circulating supply formula

- Jenkinsfile
> ci: change prod machine, change nodejs provider, alter timeout

- Jenkinsfile
> feat: feature-2.1.2

- src/app/containers/TokenDetail/Transfers.tsx
> fix: fixed transfer list search issue

- src/app/containers/HomePage/index.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
> fix: SCAN-619, SCAN-620

- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
> feat: copyright update

- src/app/components/Chart/LineChart.jsx
- src/app/components/ConnectWallet/Button.tsx
- src/app/components/ConnectWallet/Modal.tsx
- src/app/components/ConnectWallet/index.tsx
- src/app/components/ConnectWallet/useCheckHook.tsx
- src/app/components/Link/index.tsx
- src/app/components/StatsCard/index.tsx
- src/app/containers/Footer/Language.tsx
- src/app/containers/Footer/index.tsx
- src/app/containers/Header/HeaderLink.tsx
- src/app/containers/Header/index.tsx
- src/app/containers/HomePage/Notice.tsx
- src/app/containers/Statistics/index.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
- src/utils/ga.ts
- src/utils/gaConstants.ts
- src/utils/hooks/useSearch.ts
- src/utils/tableColumns/token.tsx
> feat: 1. add ga 2. update contract submit logic 3. update footer

- src/app/containers/HomePage/Notice.tsx
> fix: SCAN-652 horizontal scroll

- src/app/components/StatsCard/index.tsx
- src/app/components/TabsTablePanel/Panel.tsx
- src/app/containers/AddressContractDetail/Table.tsx
- src/app/containers/Block/BottomTablePanel.tsx
- src/app/containers/BlocksAndTransactions/index.tsx
- src/app/containers/HomePage/Notice.tsx
- src/app/containers/HomePage/index.tsx
- src/app/containers/Statistics/index.tsx
- src/app/containers/TokenDetail/Transfers.tsx
- src/app/containers/Transaction/TableCard.tsx
- src/locales/en/translation.json
- src/utils/gaConstants.ts
> feat: SCAN-596 tab change ga track

- src/app/components/Contract/index.tsx
- src/app/components/Remark/Loadable.ts
- src/app/components/Remark/index.tsx
- src/app/containers/AddressConverter/index.tsx
- src/app/containers/ContractDeployment/ContractInfo.tsx
- src/app/containers/ContractDeployment/index.tsx
- src/app/containers/Header/index.tsx
- src/app/containers/Sponsor/index.tsx
- src/app/containers/Transaction/index.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
> fix: erc1155 transfer list maybe error

- src/app/components/Chart/LineChart.jsx
- src/app/components/Chart/usePlot.js
- src/app/containers/Charts/index.jsx
- src/app/containers/TokenDetail/Basic.tsx
- src/app/containers/TokenDetail/Transfers.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
> feat: SCAN-635 SCAN-655 add stats

- src/app/components/Chart/LineChart.jsx
- src/app/components/DappButton/index.tsx
- src/app/containers/AddressContractDetail/Table.tsx
- src/app/containers/AddressConverter/index.tsx
- src/app/containers/BlocknumberCalc/index.tsx
- src/app/containers/BroadcastTx/index.tsx
- src/app/containers/TokenDetail/Basic.tsx
- src/app/containers/TokenDetail/Transfers.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
- src/utils/gaConstants.ts
> fix: feature-2.1.4 bugfix

- src/app/containers/Charts/index.jsx
> feat: hide cfx holding chart

- src/app/containers/Transaction/EventLogs/Address.tsx
- src/app/containers/Transaction/EventLogs/Data.tsx
- src/app/containers/Transaction/EventLogs/Event.tsx
- src/app/containers/Transaction/EventLogs/Loadable.ts
- src/app/containers/Transaction/EventLogs/Topics.tsx
- src/app/containers/Transaction/EventLogs/index.tsx
- src/app/containers/Transaction/TableCard.tsx
- src/app/containers/Transaction/index.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
- src/setupProxy.js
- src/utils/constants.ts
- src/utils/httpRequest.ts
> feat: add eventlogs

- src/app/components/Empty/Loadable.ts
- src/app/components/Empty/index.tsx
- src/app/components/TablePanel/Panel.tsx
- src/app/containers/Transaction/EventLogs/Topics.tsx
- src/app/containers/Transaction/EventLogs/index.tsx
> feat: add empty log placeholder, and topics address link

- src/app/components/ContractAbi/Func.tsx
> fix: write contract not support cfx value

- src/app/containers/Transaction/index.tsx
> feat: change ERC to CRC

- src/app/components/ConnectWallet/index.tsx
> feat: hide account balance if not match /swap router

- src/app/components/ConnectWallet/TxnStatusModal.tsx
- src/app/components/ConnectWallet/index.tsx
- src/app/components/StatsCard/index.tsx
- src/app/containers/Swap/index.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
- src/utils/gaConstants.ts
> fix: fixed several bugs

- config-overrides.js
https://github.com/facebook/create-react-app/issues/8320#issuecomment-623201931
> ci: fix terser resource problem

- .github/CODEOWNERS
- config-overrides.js
- src/app/containers/Transaction/EventLogs/index.tsx
- src/utils/httpRequest.ts
> feat: SCAN-896, update eventlogs api

- src/app/components/Chart/LineChart.jsx
- src/app/components/Chart/usePlot.js
- src/app/containers/Charts/index.jsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
> fix: add stats chart

- src/app/components/Chart/LineChart.jsx
> fix: chart y-axis bug

- src/app/components/Chart/LineChart.jsx
- src/app/components/Chart/usePlot.js
- src/app/containers/ChartDetail/index.tsx
- src/app/containers/Charts/index.jsx
- src/locales/en/translation.json
> feat: SCAN-1113 contract growth chart

- src/app/containers/Transaction/EventLogs/index.tsx
> fix: SCAN-1149, add token info for contract without abi

- src/app/index.tsx
> fix: SCAN-1219, fixed bignumber exponential issue

- src/app/__tests__/__snapshots__/index.test.tsx.snap
- src/app/containers/AddressContractDetail/Table.tsx
- src/app/containers/AddressContractDetail/TokenBalanceSelect.tsx
- src/app/containers/Footer/Currency.tsx
- src/app/containers/TokenDetail/Basic.tsx
- src/app/containers/TokenDetail/index.tsx
- src/app/containers/Tokens/index.tsx
- src/app/index.tsx
- src/locales/en/translation.json
- src/utils/api.ts
- src/utils/constants.ts
- src/utils/hooks/useGlobal.ts
- src/utils/tableColumns/token.tsx
> fix: 2.1.8 bugs

- src/utils/tableColumns/token.tsx
> fix: price data type

- src/app/containers/TokenDetail/Basic.tsx
- src/app/containers/TokenDetail/Transfers.tsx
- src/app/containers/TokenDetail/index.tsx
> feat: SCAN-1379 deal with unknown transferType

- src/app/containers/TokenDetail/Basic.tsx
> fix: transferType always crc20 bug

- src/app/containers/Header/Search/index.tsx
- src/locales/zh_cn/translation.json
> fix: 2.1.9 some bugs

- src/utils/hooks/useGetPendingTxnByRPC.ts
> fix: SCAN-1538, fixed first pending tx status issue

- src/app/components/TablePanel/Dropdown.tsx
- src/app/containers/Tokens/index.tsx
> fix: 2.1.9 bugs

- src/app/containers/Header/HeaderLink.tsx
- src/app/containers/Transaction/Detail.tsx
> fix: Storage Used calc

- src/app/containers/Header/Search/index.tsx
- src/utils/request.ts
> feat: SCAN-1550 optimize header search enter action

- src/app/components/AddressContainer/index.tsx
- src/app/containers/AddressContractDetail/Table.tsx
- src/utils/tableColumns/token.tsx
> feat: SCAN-1557 deal with token name

- src/app/components/Text/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/Tooltip/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/Tooltip/index.tsx
- src/app/components/TxnComponents/ContractDetail.tsx
- src/app/components/TxnComponents/Event.tsx
- src/app/components/TxnComponents/InputData/Common.tsx
- src/app/components/TxnComponents/InputData/GeneralDecode.tsx
- src/app/components/TxnComponents/InputData/JsonDecode.tsx
- src/app/components/TxnComponents/InputData/OptimizationDecode.tsx
- src/app/components/TxnComponents/InputData/Original.tsx
- src/app/components/TxnComponents/InputData/UTF8.tsx
- src/app/components/TxnComponents/InputData/index.tsx
- src/app/components/TxnComponents/index.tsx
- src/app/components/TxnComponents/util.ts
- src/app/containers/AddressContractDetail/ContractDetailPage.tsx
- src/app/containers/AddressContractDetail/Table.tsx
- src/app/containers/AddressContractDetail/__tests__/__snapshots__/AddressDetailPage.test.tsx.snap
- src/app/containers/AddressContractDetail/__tests__/__snapshots__/ContractDetailPage.test.tsx.snap
- src/app/containers/TokenDetail/index.tsx
- src/app/containers/Transaction/Detail.tsx
- src/app/containers/Transaction/EventLogs/Address.tsx
- src/app/containers/Transaction/EventLogs/Data.tsx
- src/app/containers/Transaction/EventLogs/Topics.tsx
- src/app/containers/Transaction/EventLogs/index.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
- src/styles/global-styles.ts
- src/utils/tableColumns/token.tsx
> Feature 2.2.0

- src/app/__tests__/__snapshots__/index.test.tsx.snap
- src/app/components/NFTPreview/NFTInfo.ts
- src/app/components/NFTPreview/index.tsx
- src/app/components/NFTPreview/utils.ts
- src/app/components/TablePanel/Panel.tsx
- src/app/containers/AddressContractDetail/ContractMetadata.tsx
- src/app/containers/Header/HeaderLink.tsx
- src/app/containers/Header/index.tsx
- src/app/containers/NFTChecker/Loadable.tsx
- src/app/containers/NFTChecker/index.tsx
- src/app/containers/NFTChecker/scanUtilAbi.ts
- src/app/containers/NFTChecker/utils.ts
- src/app/index.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
- src/utils/gaConstants.ts
> feat: SCAN-1490 add NFT checker tool

- src/app/containers/Header/Search/index.tsx
- src/app/containers/NFTChecker/index.tsx
> fix: 2.2.0 some bugs

- src/app/components/TxnComponents/ContractDetail.tsx
> fix: fixed txn detail contract info link issue

- src/app/components/NFTPreview/index.tsx
- src/app/components/NFTPreview/utils.ts
- src/app/components/TxnComponents/ContractDetail.tsx
- src/app/components/TxnComponents/InputData/OptimizationDecode.tsx
- src/app/containers/NFTChecker/index.tsx
- src/app/containers/NFTChecker/utils.ts
- src/styles/global-styles.ts
- src/utils/tableColumns/token.tsx
> fix: hotfix issues

- src/app/components/TxnComponents/InputData/OptimizationDecode.tsx
> fix: SCAN-1727, title align issue

- src/app/components/TxnComponents/Event.tsx
- src/app/components/TxnComponents/InputData/GeneralDecode.tsx
- src/app/components/TxnComponents/InputData/OptimizationDecode.tsx
> fix: crash when decodedData is undefined

- src/app/containers/AddressContractDetail/ContractContent.tsx
- src/app/containers/AddressContractDetail/Table.tsx
- src/app/containers/ContractVerification/index.tsx
- src/app/containers/TokenDetail/Transfers.tsx
- src/utils/tableColumns/transaction.tsx
> feat: add features

- src/app/components/TxnComponents/TokenTransfer.tsx
- src/app/components/TxnComponents/TokenTypeTag.tsx
- src/app/containers/ContractVerification/index.tsx
- src/app/containers/Transaction/Detail.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
> fix: fixed issues

- src/app/components/Contract/index.tsx
- src/app/components/DappButton/index.tsx
- src/app/components/Empty/index.tsx
- src/app/components/StatsCard/index.tsx
- src/app/components/TablePanel/Datepicker.tsx
- src/app/containers/AddressContractDetail/ContractContent.tsx
- src/app/containers/AddressContractDetail/ContractDetailPage.tsx
- src/app/containers/AddressContractDetail/Table.tsx
- src/app/containers/Contract/index.tsx
- src/app/containers/ContractVerification/index.tsx
- src/app/containers/NFTChecker/index.tsx
- src/app/containers/TokenDetail/Transfers.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
> fix: Feature 2.2.1 bugs

- src/app/components/ConnectWallet/Button.tsx
> fix: SCAN-1863 address format

- src/app/containers/Header/Search/index.tsx
- src/locales/zh_cn/translation.json
> fix: fixed typo issue

- src/app/components/ConnectWallet/Button.tsx
- src/app/components/ConnectWallet/__tests__/__snapshots__/index.test.tsx.snap
- src/app/containers/Transaction/index.tsx
> feat: hide internal trace tab by txn detail info

- src/app/components/ConnectWallet/History.tsx
- src/app/components/ConnectWallet/Modal.tsx
> fix: SCAN-1866, update connect wallet address format

- src/app/containers/AddressContractDetail/ContractDetailPage.tsx
> fix: SCAN-1884, official website link issue

- src/app/components/Contract/index.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
> feat: SCAN-1858 not support 0x for contract register

- src/app/containers/AddressContractDetail/Table.tsx
- src/app/containers/AddressConverter/index.tsx
- src/app/containers/Block/index.tsx
- src/app/containers/Blocks/index.tsx
- src/app/containers/HomePage/index.tsx
- src/utils/tableColumns/block.tsx
> feat: SCAN-1833 optimize epoch pivot

- src/app/components/QrcodeButton/index.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
> feat: SCAN-1683 optimize QR code

- src/app/components/QrcodeButton/index.tsx
> feat: fixed issues

- src/utils/httpRequest.ts
> fix: fixed url prefix issue

- src/app/components/NFTPreview/utils.ts
- src/utils/contract/crc1155core.json
> fix: crc-721 nft preview support

- package.json
- src/app/components/TablePanelNew/index.tsx
- src/app/containers/AddressContractDetail/ContractDetailPage.tsx
- src/app/containers/AddressConverter/index.tsx
- src/app/containers/Blocks/MinedBlocks.tsx
- src/app/containers/Footer/__tests__/index.test.tsx
- src/app/containers/Transactions/CFXTxns.tsx
- src/app/containers/Transactions/CRC1155Txns.tsx
- src/app/containers/Transactions/CRC20Txns.tsx
- src/app/containers/Transactions/CRC721Txns.tsx
- src/app/containers/Transactions/Common.tsx
- src/app/containers/Transactions/ExcutedTxns.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
- src/utils/cfx.ts
- src/utils/tableColumns/token.tsx
- yarn.lock
> feat: add features and fixed bugs

- src/app/containers/BalanceChecker/Result.tsx
> feat: Feature 2.2.3

- src/app/components/ConnectWallet/Modal.tsx
- src/app/components/ConnectWallet/index.tsx
- src/app/containers/HomePage/Notice.tsx
- src/app/containers/Notices/notices.ts
- src/utils/hooks/usePortal.ts
> feat: SCAN-2176, update notice

- src/app/components/Contract/index.tsx
- src/app/components/TxnComponents/util.ts
- src/utils/contractManagerTool.ts
- src/utils/index.ts
- src/utils/tableColumns/transaction.tsx
> fix: hotfix v2.2.3

- src/app/components/AddressContainer/index.tsx
- src/app/components/TxnComponents/TokenTransfer.tsx
- src/app/containers/AddressContractDetail/ContractMetadata.tsx
- src/app/containers/Transaction/Detail.tsx
- src/utils/tableColumns/token.tsx
> feat: fixed bugs

- src/app/components/NFTPreview/index.tsx
> fix: SCAN-2319, show not found if network crash in NFT preview

- src/app/containers/HomePage/Notice.tsx
- src/app/containers/Notices/notices.ts
- src/index.tsx
> feat: update notice to v2.2.4

- src/app/components/Contract/index.bak.tsx
- src/app/components/TablePanel/Dropdown.tsx
- src/app/containers/AddressContractDetail/Table.tsx
- src/app/containers/Blocks/MinedBlocks.tsx
- src/app/containers/Epoch/index.tsx
- src/app/containers/NFTChecker.bak/index.tsx
- src/app/containers/TokenDetail/Transfers.tsx
- src/app/containers/Tokens/Transfers.tsx
- src/app/containers/Transactions/CFXTxns.tsx
- src/app/containers/Transactions/CRC1155Txns.tsx
- src/app/containers/Transactions/CRC20Txns.tsx
- src/app/containers/Transactions/CRC721Txns.tsx
- src/app/containers/Transactions/ExcutedTxns.tsx
- src/app/containers/Transactions/PendingTxns.tsx
- src/app/containers/Transactions/components/AdvancedSearchForm.tsx
- src/app/containers/Transactions/components/DebounceTokenSelect.tsx
- src/app/containers/Transactions/components/index.tsx
- src/app/containers/_Benchmark/index.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
- src/styles/global-styles.ts
- src/utils/httpRequest.ts
- src/utils/index.ts
- src/utils/tableColumns/block.tsx
> feat: add advanced search

- src/app/components/Contract/index.tsx
> fix: SCAN-2534，update contract info error

- src/index.tsx
> feat: update release version in console

- src/app/containers/Footer/index.tsx
- src/app/containers/Header/index.tsx
- src/app/containers/HomePage/Notice.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
- src/utils/gaConstants.ts
> feat: add notice link and developer api entry

- src/app/containers/Contracts/RegisteredContracts.tsx
- src/app/containers/Contracts/index.tsx
- src/app/containers/TokenDetail/Holders.tsx
- src/app/containers/Tokens/index.tsx
- src/utils/tableColumns/token.tsx
- src/utils/tableColumns/utils.tsx
> feat: SCAN-2562, upgrade tokenColumn.number fn

- src/app/components/DownloadCSV/index.tsx
- src/app/components/Empty/index.tsx
- src/app/components/ProjectInfo/index.tsx
- src/app/components/TablePanelNew/index.tsx
- src/app/containers/AddressContractDetail/AddressDetailPage.tsx
- src/app/containers/AddressContractDetail/ContractContent.tsx
- src/app/containers/AddressContractDetail/layouts.ts
- src/app/containers/HomePage/BlockchainInfo.tsx
- src/app/containers/TokenDetail/index.tsx
- src/app/containers/Tokens/index.tsx
- src/app/containers/Transactions/components/AdvancedSearchForm.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
- src/styles/global-styles.ts
> feat: add features from 2.2.6 branch

- src/app/containers/Transactions/CFXTxns.tsx
> feat: SCAN-2439, add create contract option to cfx txns list filter

- src/app/components/TablePanelNew/index.tsx
- src/app/containers/Notices/index.tsx
- src/app/containers/Tokens/index.tsx
- src/index.tsx
> feat: 1. update notice, 2. update token list pageSize

- src/app/containers/Tokens/index.tsx
- src/utils/tableColumns/utils.tsx
> feat: SCAN-2723, update token util.number fn, fix long string issue

- src/app/containers/NFTChecker/index.tsx
> fix: SCAN-2724, fixed nft checker same nft name issue

- src/app/components/ProjectInfo/index.tsx
- src/app/components/TablePanelNew/index.tsx
- src/app/containers/Tokens/index.tsx
> feat: SCAN-2634, support securityCredits in token list

- src/app/components/ProjectInfo/index.tsx
- src/app/components/TablePanelNew/index.tsx
- src/app/containers/NFTChecker/index.tsx
- src/app/containers/Tokens/index.tsx
> hotfix: SCAN-2634, support securityCredits in token list

- src/app/components/Chart/DataZoomLineChart.tsx
- src/app/components/Chart/LineChart.jsx
- src/app/components/Contract/index.tsx
- src/app/components/ProjectInfo/index.tsx
- src/app/containers/AddressContractDetail/ContractDetailPage.tsx
- src/app/containers/Blocks/Dag/index.tsx
- src/app/containers/Blocks/index.tsx
- src/app/containers/Header/Search/index.tsx
- src/app/containers/HomePage/BlockchainInfo.tsx
- src/app/containers/TokenDetail/Basic.tsx
- src/app/containers/Tokens/Transfers.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
- src/utils/contractManagerTool.ts
> feat: update features

- src/app/containers/Sponsor/index.tsx
- src/utils/sponsorFaucet/faucet.js
> fix: SCAN-2790, fixed sponsor issue

- src/app/components/ProjectInfo/icons.tsx
- src/app/components/ProjectInfo/index.tsx
> feat: SCAN-2826, update project info

- src/app/containers/Notices/index.tsx
- src/app/containers/Sponsor/index.tsx
- src/index.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
> feat: update release info 

- src/app/components/ConnectWallet/TxnStatusModal.tsx
- src/app/components/ContractAbi/Func.tsx
- src/app/components/DappButton/index.tsx
- src/app/containers/AddressContractDetail/AddressDetailPage.tsx
- src/app/containers/BroadcastTx/index.tsx
- src/app/containers/ContractDeployment/ContractInfo.tsx
- src/app/containers/ContractDeployment/index.tsx
- src/app/containers/Swap/index.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
- src/utils/index.ts
> feat: upgrade contract react result modal, support show tx status

- src/app/containers/FCCFX/ActionField.tsx
- src/app/containers/FCCFX/index.tsx
> feat: fixed button disabled and loading issue

- src/app/components/StatsCard/index.tsx
- src/app/index.tsx
> fix: fixed top accounts by gas used percent issue

- src/app/components/StatsCard/index.tsx
> feat: support 0 value of top statistcs overview section

- src/app/index.tsx
- src/utils/index.ts
> feat: handle invalid conflux hex address

- src/app/index.tsx
> fix: SCAN-3243, fixed nft-checker redirect issue

- src/app/index.tsx
> fix: SCAN-3292, fixed nft-checker router issue

- src/app/containers/HomePage/BlockchainInfo.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
- src/utils/httpRequest.ts
> feat: SCAN-3275, update block info on homepage

- src/app/components/Chart/SmallChart.jsx
- src/app/containers/HomePage/BlockchainInfo.tsx
> feat: add transfer tps

- src/app/components/Chart/SmallChart.jsx
- src/app/containers/HomePage/BlockchainInfo.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
- src/utils/httpRequest.ts
> feat: add token transfer tps

- src/app/containers/Notices/index.tsx
- src/index.tsx
> feat: SCAN-3130, update release version and notice

- .circleci/config.yml
- yarn.lock
> feat: update node version of CircleCI config.yml

- .circleci/config.yml
- package.json
- src/index.tsx
> test: update console log version from 2.3.1 to 2.3.2

- src/app/containers/Sponsor/index.tsx
> feat: SCAN-3404, optimized sponsor gasBound&storageBound value

- package.json
- src/app/containers/AddressContractDetail/AddressDetailPage.tsx
- src/utils/constants.ts
- src/utils/index.ts
- yarn.lock
> feat: remove internalcontract reentryConfig

- src/app/containers/Notices/index.tsx
- src/index.tsx
> feat: SCAN-3293, update release version and notice

- src/app/containers/AddressContractDetail/AddressMetadata.tsx
- src/app/containers/Header/index.tsx
> feat: SCAN-3448, update goverance link of testnet

- src/app/components/Chart/Chart.jsx
- src/app/components/Chart/LineChart.jsx
- src/app/components/Chart/usePlot.js
- src/app/containers/FCCFX/AccountInfoCard.tsx
- src/app/containers/FCCFX/ActionField.tsx
- src/app/containers/FCCFX/Common.tsx
- src/app/containers/FCCFX/StakeAndSignCard.tsx
- src/app/containers/FCCFX/TotalInfoCard.tsx
- src/app/containers/FCCFX/WithdrawCFXCard.tsx
- src/app/containers/HomePage/BlockchainInfo.tsx
- src/app/containers/TokenDetail/index.tsx
- src/app/containers/pos/HomePage/BlockchainInfo.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
- src/utils/constants.ts
- src/utils/tableColumns/pos/committee.tsx
> feat: 1. fixed bugs of PoS 2. fixed charts request issue

- src/app/containers/FCCFX/AccountInfoCard.tsx
> feat: add warning condition to unsigned fc of fccfx page

- src/app/components/TxnComponents/Overview.tsx
- src/app/components/TxnComponents/Status.tsx
- src/app/containers/Transaction/Detail.tsx
- src/utils/tableColumns/transaction.tsx
> fix: SCAN-3509, update tx status error message handler

- src/app/containers/Block/DescriptionPanel.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
- src/setupProxy.js
> feat: SCAN-3528, SCAN-3527, update proxy config

- src/utils/sponsorFaucet/faucet.js
> feat: update sponsor address to lowercase

- src/app/containers/Header/index.tsx
> feat: SCAN-3554, add evm space scan link

- src/app/containers/Header/index.tsx
- src/utils/sponsorFaucet/faucet.js
> feat: add evm space scan network link

- src/app/containers/Header/index.tsx
> feat: update evm space network link title

- src/app/containers/Header/index.tsx
- src/app/containers/NetworkError/index.tsx
- src/utils/index.ts
> fix: SCAN-3554, add hostname suffix check

- src/app/containers/Header/index.tsx
> feat: SCAN-3557, update evm space network title

- src/app/containers/AddressContractDetail/AddressMetadata.tsx
> fix: fixed publishRequestError error in AddressMetadata.ts

- src/utils/index.ts
> feat: SCAN-3628, upgrade error Notification detail info handler

- src/app/containers/Accounts/index.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
- src/styles/global-styles.ts
> feat: SCAN-3637, add top N download

- src/app/containers/Header/index.tsx
- src/utils/index.ts
> feat: SCAN-3640, upgrade network config and link

- src/utils/index.ts
> fix: fixed network link issue

- src/app/components/ConnectWallet/Modal.tsx
- src/app/containers/Footer/index.tsx
- src/app/containers/Sponsor/index.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
- src/utils/gaConstants.ts
- src/utils/hooks/usePortal.ts
> feat: update portal to fluent, include i18n

- src/utils/hooks/useConfirmRisk.ts
> feat: temporary disabled tx get pos confirm status

- src/utils/constants.ts
> feat: update new fccfx contract address

- package.json
- yarn.lock
> feat: update js conflux SDK to v2.0.2

- src/utils/hooks/useConfirmRisk.ts
> feat: reset getPosStatus of Security component

- src/app/components/InfoIconWithTooltip/index.tsx
- src/app/containers/HomePage/BlockchainInfo.tsx
- src/app/containers/pos/HomePage/BlockchainInfo.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
> feat: SCAN-3674, add pos APY to homepage

- src/app/containers/HomePage/BlockchainInfo.tsx
> feat: update column sort

- src/app/containers/pos/HomePage/BlockchainInfo.tsx
> feat: update pos homepage summary info sort

- src/app/components/ContractAbi/index.tsx
- src/app/containers/AddressContractDetail/ContractContent.tsx
> fix: proxy contract call issue

- src/app/components/ContractAbi/index.tsx
- src/app/containers/AddressContractDetail/ContractContent.tsx
- src/app/containers/pos/HomePage/BlockchainInfo.tsx
> fix: fixed proxy contract read&write issue

- src/app/components/ContractAbi/index.tsx
> fix: fixed to address issue of proxy contract

- src/app/components/ContractAbi/index.tsx
- src/app/containers/AddressContractDetail/ContractContent.tsx
> fix: fixed write proxy contract to address issue

- src/app/containers/FCCFX/AccountInfoCard.tsx
> feat: update fccfx profit value condition

- src/app/containers/Notices/index.tsx
- src/index.tsx
> feat: update release notice

- src/app/containers/Transactions/CFXTxns.tsx
> fix: remove tx create type in tx transfer filter

- src/utils/constants.ts
> fix: fix dev env condition

- src/app/components/TxnComponents/Overview.tsx
- src/app/components/TxnComponents/Status.tsx
- src/app/containers/Notices/index.tsx
- src/app/containers/Transaction/Detail.tsx
- src/index.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
- src/utils/tableColumns/transaction.tsx
> feat: SCAN-3758, add pending reason link to tx detail page

- src/app/containers/Transactions/InternalTxns.tsx
> fix: fixed null trace condition issue

- src/app/components/StatsCard/index.tsx
- src/app/containers/Transactions/InternalTxns.tsx
> fix: fixed wallet accounts dependace issue

- src/app/components/TxnComponents/InputData/index.tsx
- src/app/containers/Transaction/EventLogs/index.tsx
- src/setupProxy.js
> feat: optimize proxy contract inputdata&eventlog decode

- src/app/containers/pos/Account/Overview.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
> feat: update i18n of retired rights

- src/app/containers/pos/Account/Overview.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
> feat: update retired rights i18n to retired block number

- package.json
- src/app/components/ContractAbi/index.tsx
- yarn.lock
> feat: optimize individual contract read request to batch request

- src/app/components/DownloadCSV/index.tsx
- src/app/containers/Report/index.tsx
> feat: update google recapture sitekey

- src/app/containers/Notices/index.tsx
- src/app/containers/pos/Account/VotingHistory.tsx
- src/index.tsx
- src/utils/rpcRequest.ts
- src/utils/tableColumns/utils.tsx
> fix: compatible with changed of rpc response

- src/app/components/TablePanelNew/index.tsx
- src/app/containers/pos/Account/VotingHistory.tsx
> feat: orderby params of url accept non-string types

- src/locales/zh_cn/translation.json
> feat: update i18n

- src/app/components/AddressContainer/index.tsx
- src/app/components/ConnectWallet/Modal.tsx
- src/app/components/ContractAbi/index.tsx
- src/app/components/QrcodeButton/index.tsx
- src/app/containers/Blocks/MinedBlocks.tsx
- src/app/containers/Notices/index.tsx
- src/app/containers/Transaction/Detail.tsx
- src/app/containers/Transactions/InternalTxns.tsx
- src/index.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
- src/setupProxy.js
- src/utils/index.ts
- src/utils/tableColumns/token.tsx
> feat: support espace hex address

- src/app/components/AddressContainer/index.tsx
- src/app/components/ConnectWallet/Modal.tsx
- src/app/components/ContractAbi/index.tsx
- src/app/components/QrcodeButton/index.tsx
- src/app/containers/Blocks/MinedBlocks.tsx
- src/app/containers/Notices/index.tsx
- src/app/containers/Transaction/Detail.tsx
- src/app/containers/Transactions/InternalTxns.tsx
- src/index.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
- src/setupProxy.js
- src/utils/index.ts
- src/utils/tableColumns/token.tsx
> feat: relase v2.8.2

- src/app/components/AddressContainer/index.tsx
- src/app/containers/Notices/index.tsx
- src/index.tsx
- src/utils/index.ts
> feat: fixed espace link host network issue

- src/app/components/Contract/index.tsx
> feat: update token icon check order

- src/app/containers/Transaction/Detail.tsx
> fix: fixed SCAN-3845

- src/app/components/Contract/index.tsx
- src/app/containers/Transaction/Detail.tsx
> hotfix: fixed SCAN-3845

- src/app/components/NFTPreview/index.tsx
- src/app/containers/NFTChecker/index.tsx
- src/app/containers/NFTDetail/index.tsx
> feat: and NFT detail entry, remove NFT checker contract type limit

- src/app/containers/FCCFX/TotalInfoCard.tsx
- src/app/containers/FCCFX/index.tsx
> feat: use zero address to get FCCFX summary info

- src/app/containers/FCCFX/Common.tsx
> fix: fccfx page with no wallet provider issue

- src/app/containers/Notices/index.tsx
- src/index.tsx
> feat: update release version and notice link

- src/app/containers/AddressContractDetail/ContractContent.tsx
- src/app/containers/AddressContractDetail/ContractMetadata.tsx
- src/app/containers/AddressContractDetail/Table.tsx
> feat: optimize 0x bytecode contract display in contract detail page

- src/app/containers/NFTDetail/TransferModal.tsx
> feat: disabled tranfer if not owner of NFT

- src/app/containers/NFTDetail/TransferList.tsx
- src/app/containers/NFTDetail/index.tsx
> feat: optimize NFT detail with error response data

- src/app/containers/Notices/index.tsx
- src/index.tsx
> feat: update release note and version number

- src/app/components/Charts/ChartTemplate.tsx
> feat: remove sort in ChartTemplate

- src/app/containers/NewCharts/TxTest.tsx
- src/app/index.tsx
> feat: add test chart

- src/app/components/Charts/StockChartTemplate.tsx
> feat: disable highcharts datagrouping

- src/app/containers/Charts/Token.tsx
> fix: SCAN-3978

- src/app/index.tsx
> feat: initial dayjs lang

- src/app/components/Contract/index.tsx
- src/app/containers/Contract/index.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
- src/utils/contractManagerTool.ts
> feat: add token ipfs gateway config

- src/app/components/Charts/ChartTemplate.tsx
- src/app/components/Charts/StockChartTemplate.tsx
- src/app/components/Contract/index.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
> feat: update ipfs gateway

- src/app/containers/Notices/index.tsx
- src/index.tsx
> feat: update release note and link

- src/app/containers/Charts/index.tsx
> fix: fixed dayjs locale issue in chart preview page

- src/app/containers/NFTAsset/index.tsx
> fix: SCAN-4011

- src/app/containers/HomePage/BlockchainInfo.tsx
- src/app/containers/Notices/index.tsx
- src/index.tsx
> feat: update release info

- src/app/components/Text/index.tsx
- src/app/containers/Notices/index.tsx
- src/index.tsx
> fix: fixed tooltip title info click isse

- src/app/components/Text/index.tsx
- src/app/containers/HomePage/BlockchainInfo.tsx
- src/app/containers/Notices/index.tsx
- src/index.tsx
> feat: release v2.12.1

- src/app/containers/NFTAsset/index.tsx
- src/app/containers/NFTDetail/index.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
> feat: upgrade NFT asset list and detail

- src/app/containers/Charts/crossSpace/DailyCFXTransfer.tsx
- src/app/containers/Charts/pos/DailyRewardRank.tsx
- src/utils/constants.ts
> feat: update daily CFX transfer chart of cross space

- src/app/containers/Charts/pos/DailyAPY.tsx
- src/app/containers/Charts/pos/DailyParticipation.tsx
- src/app/containers/Charts/pos/index.tsx
> feat: update chart type in rate chart of PoS

- src/app/containers/Charts/crossSpace/index.tsx
- src/app/containers/Charts/pos/index.tsx
- src/app/containers/Charts/pow/index.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
> feat: bug fix

- src/app/containers/Charts/crossSpace/Contract.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
> fix: fixed pos charts issue

- src/app/containers/Charts/crossSpace/index.tsx
- src/app/containers/Charts/pow/index.tsx
- src/app/containers/Notices/index.tsx
- src/index.tsx
> feat: update release note link and version

- src/app/containers/Charts/crossSpace/index.tsx
- src/app/containers/Charts/pos/index.tsx
- src/app/containers/Charts/pow/index.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
> feat: update charts i18n

- src/app/components/ConnectWallet/Modal.tsx
- src/app/components/TxnComponents/Overview.tsx
- src/app/components/TxnComponents/Status.tsx
- src/app/containers/NFTAsset/index.tsx
- src/app/containers/Transaction/Detail.tsx
- src/app/containers/Transactions/PendingTxns.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
- src/setupProxy.js
- src/utils/constants.ts
- src/utils/hooks/usePortal.ts
- src/utils/httpRequest.ts
- src/utils/rpcRequest.ts
- src/utils/tableColumns/PendingReason.tsx
- src/utils/tableColumns/transaction.tsx
> feat: add s39 features

- src/app/containers/pos/Account/RightStatus.tsx
> fix: SCAN-4109

- src/app/containers/HomePage/BlockchainInfo.tsx
- src/app/containers/pos/HomePage/BlockchainInfo.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
> feat: add chart detail link to pos preivew title

- src/app/components/AddressContainer/index.tsx
- src/app/components/ConnectWallet/Button.tsx
- src/app/containers/AddressContractDetail/AddressDetailPage.tsx
- src/app/containers/AddressContractDetail/ContractDetailPage.tsx
- src/app/containers/Header/index.tsx
- src/app/containers/Profile/AddressLabel.tsx
- src/app/containers/Profile/CreateAddressLabel.tsx
- src/app/containers/Profile/CreateTxNote.tsx
- src/app/containers/Profile/Loadable.tsx
- src/app/containers/Profile/TxNote.tsx
- src/app/containers/Profile/index.tsx
- src/app/containers/Transaction/Detail.tsx
- src/app/index.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
- src/setupProxy.js
- src/styles/global-styles.ts
- src/utils/constants.ts
- src/utils/gaConstants.ts
- src/utils/tableColumns/token.tsx
> feat: add profile

- src/app/components/AddressContainer/index.tsx
- src/app/components/ConnectWallet/Button.tsx
- src/app/components/ContractAbi/OutputItem.tsx
- src/app/components/NFTPreview/index.tsx
- src/app/containers/Header/index.tsx
- src/app/containers/NFTDetail/index.tsx
- src/app/containers/Profile/CreateAddressLabel.tsx
- src/app/containers/Profile/CreateTxNote.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
- src/styles/global-styles.ts
- src/utils/api.ts
> fix: fixed user address name tag issues

- src/app/components/TxnComponents/AddressLabel.tsx
- src/app/components/TxnComponents/InputData/OptimizationDecode.tsx
- src/app/containers/Transaction/EventLogs/Address.tsx
- src/app/containers/Transaction/EventLogs/Data.tsx
- src/app/containers/Transaction/EventLogs/Topics.tsx
- src/app/containers/Transaction/EventLogs/index.tsx
> fix: SCAN-4181, SCAN-4182

- src/utils/hooks/useGlobal.ts
> fix: fixed globalData property issue

- src/app/components/ConnectWallet/Button.tsx
> fix: fixed address name tag issue of connect wallet button

- src/utils/hooks/useGlobal.ts
> fix: fixed address name tag issue

- src/app/components/AddressContainer/index.tsx
- src/app/containers/Transaction/EventLogs/Address.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
> feat: optimize address name tag in AddresssContainer

- src/app/containers/Notices/index.tsx
- src/index.tsx
> feat: update release version and note link

- src/app/containers/Profile/File.tsx
- src/locales/en/translation.json
> feat: add max records check

- src/app/containers/Profile/File.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
> feat: 1. add import update amount 2. update download file suffix

- src/app/containers/Profile/File.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
- src/utils/constants.ts
> feat: upgrade profile export&import

- src/app/containers/Charts/crossSpace/DailyCFXTransferCount.tsx
- src/app/containers/Charts/crossSpace/Loadable.tsx
- src/app/containers/Charts/crossSpace/index.tsx
- src/app/containers/Charts/pos/DailyRewardInfo.tsx
- src/app/containers/Charts/pos/Loadable.tsx
- src/app/containers/Charts/pos/index.tsx
- src/app/containers/pos/IncomingRank/IncomingRankList.tsx
- src/app/containers/pos/IncomingRank/Leaderboard.tsx
- src/app/containers/pos/IncomingRank/Loadable.tsx
- src/app/containers/pos/IncomingRank/index.tsx
- src/app/index.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
- src/utils/constants.ts
- src/utils/tableColumns/pos/incomingRank.tsx
> feat: add new pos charts and rank list

- src/app/components/TablePanelNew/index.tsx
- src/app/containers/pos/IncomingRank/Leaderboard.tsx
- src/utils/tableColumns/pos/incomingRank.tsx
> feat: add pagination and sort to pos income rank more list

- src/app/containers/pos/IncomingRank/Leaderboard.tsx
- src/setupProxy.js
> feat: add default sort key to pos income rank list

- src/app/containers/pos/IncomingRank/Leaderboard.tsx
- src/utils/tableColumns/pos/incomingRank.tsx
> feat: update style of pos income rank

- src/app/containers/Profile/CreateAddressLabel.tsx
- src/app/containers/Profile/CreateTxNote.tsx
> fix: SCAN-4237

- src/app/containers/Blocks/Dag/lib-dag.js
- src/utils/request.ts
> feat: reset backend response refactor compatible

- src/app/containers/Blocks/Dag/lib-dag.js
- src/utils/request.ts
> feat: update util fn request and dag

- src/app/components/TablePanelNew/index.tsx
- src/locales/zh_cn/translation.json
> fix: fixed table sort issue

- src/app/containers/BalanceChecker/Result.tsx
- src/app/containers/Report/index.tsx
- src/app/containers/Transactions/components/DebounceTokenSelect.tsx
> feat: compatible with scan backend api upgrade

- src/app/containers/Header/index.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
- src/utils/gaConstants.ts
> feat: add faucet to tools

- src/app/containers/Notices/index.tsx
- src/index.tsx
> feat: update release note and version

- src/app/containers/Notices/index.tsx
- src/index.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
> fix: hotfix for pending reason issue

- src/app/containers/NFTDetail/index.tsx
- src/app/containers/Transaction/Detail.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
- src/utils/constants.ts
- src/utils/httpRequest.ts
> feat: add NFT metadata refresh

- src/app/components/NFTPreview/index.tsx
- src/utils/request.ts
> fix: fixed HEAD request issue

- src/app/components/NFTPreview/index.tsx
- src/utils/request.ts
> fix: hotfix for HEAD request issue

- src/app/containers/Notices/index.tsx
- src/index.tsx
- src/utils/index.ts
> feat: update error code tip

- src/app/containers/AddressContractDetail/AddressMetadata.tsx
- src/app/containers/Header/index.tsx
> feat: update governance website link

- src/locales/zh_cn/translation.json
> feat: update miner zh i18n of top statistic

- src/locales/zh_cn/translation.json
> feat: replace miner text in top statistics

- src/app/containers/Footer/index.tsx
- src/utils/constants.ts
> feat: hide sensitive info

- src/app/containers/Footer/index.tsx
- src/utils/constants.ts
> feat: update footer item

- src/app/components/AddressContainer/index.tsx
- src/app/components/ConnectWallet/Button.tsx
- src/app/components/NFTPreview/index.tsx
- src/app/components/TxnComponents/AddressLabel.tsx
- src/app/containers/AddressContractDetail/AddressDetailPage.tsx
- src/app/containers/AddressContractDetail/ContractDetailPage.tsx
- src/app/containers/AddressContractDetail/layouts.ts
- src/app/index.tsx
- src/setupProxy.js
- src/styles/global-styles.ts
- src/styles/variable.ts
- src/utils/constants.ts
- src/utils/hooks/useENS.ts
- src/utils/hooks/useGlobal.ts
- src/utils/httpRequest.ts
- src/utils/index.ts
- src/utils/request.ts
> feat: sync cns

- src/app/containers/Header/HeaderLink.tsx
> feat: change header link color on mobile platform

- src/app/containers/AddressContractDetail/ContractContent.tsx
- src/app/containers/ContractVerification/index.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
- src/setupProxy.js
- src/utils/httpRequest.ts
> feat: add library support to contract verify and check status

- src/app/components/AddressContainer/index.tsx
> fix: fixed contract creattion ens issue

- src/app/containers/AddressContractDetail/ContractContent.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
> feat: add evm version in contract verify check

- src/app/containers/AddressContractDetail/layouts.ts
> fix: make ens name to lowercase string of address tile

- src/app/containers/ContractVerification/index.tsx
> feat: add default value to contract library veriry

- src/app/containers/ContractVerification/index.tsx
> feat: update default value to contract library veriry

- src/images/logo-cns.svg
- src/utils/constants.ts
> feat: update cns contract address and logo

- src/app/containers/ContractVerification/index.tsx
> fix: fixed null library issue when contract verify submit

- src/app/components/NFTPreview/index.tsx
> feat: add fallback image to NFTPreview

- src/app/components/NFTPreview/index.tsx
- src/app/components/Text/index.tsx
- src/app/containers/NFTDetail/index.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
> feat: enhancement NFT detail to show more info

- src/app/containers/NFTDetail/index.tsx
> feat: remove duplicate description panel of NFT detail

- src/app/containers/AddressContractDetail/ContractContent.tsx
> fix: fixed SDK init contract error

- src/app/components/NFTPreview/3D.tsx
- src/app/components/NFTPreview/index.tsx
- src/app/containers/NFTDetail/index.tsx
> feat: fixed 3d uri issue

- package-lock.json
- src/app/components/ErrorBoundary/index.tsx
- src/app/components/NFTPreview/3D.tsx
- src/app/components/NFTPreview/index.tsx
- src/app/components/NFTPreview/scene/FBX.tsx
- src/app/components/NFTPreview/scene/GLTF.tsx
- src/app/components/NFTPreview/scene/OBJ.tsx
- src/app/components/NFTPreview/scene/index.tsx
> feat: add .obj .fbx format support of 3D NFT, and error handler

- src/app/containers/Notices/index.tsx
- src/index.tsx
- src/utils/ens/index.ts
- src/utils/hooks/useENS.ts
> feat: 1. disable ENS 2. update version

- src/app/containers/NFTDetail/index.tsx
> feat: optimize NFT trait card style

- src/app/containers/NFTDetail/index.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
> feat: update rights year

- src/app/components/ConnectWallet/Button.tsx
- src/app/components/ConnectWallet/useCheckHook.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
> fix: fixed connect wallet issue

- src/app/containers/AddressContractDetail/ContractContent.tsx
> fix: fixed contract read issue

- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
- src/utils/tableColumns/PendingReason.tsx
> feat: add pending tx handler of error code 20

- src/app/components/TxnComponents/GasFee.tsx
- src/app/containers/Transaction/Detail.tsx
- src/utils/index.ts
- src/utils/tableColumns/block.tsx
- src/utils/tableColumns/transaction.tsx
> feat: update gas price and gas fee unit

- src/app/components/TxnComponents/GasFee.tsx
- src/app/containers/Transaction/Detail.tsx
> feat: show full length gas fee value of tx detail

- src/utils/ens/index.ts
- src/utils/hooks/useENS.ts
> feat: show ens info

- src/app/containers/CoreID/index.tsx
> fix: fixed coreid user domains duplicate issue

- src/app/containers/AddressContractDetail/ContractContent.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
> feat: support show multiple verified sourcecode by hardhat compile

- src/app/containers/Charts/nft/Assets.tsx
- src/app/containers/Charts/nft/Contracts.tsx
- src/app/containers/Charts/nft/Holders.tsx
- src/app/containers/Charts/nft/Transfers.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
- src/utils/index.ts
> feat: update nft charts i18n

- src/app/containers/Charts/nft/Assets.tsx
- src/app/containers/Charts/nft/Contracts.tsx
- src/app/containers/Charts/nft/Holders.tsx
- src/app/containers/Charts/nft/Transfers.tsx
- src/app/containers/Charts/pos/DailyRewardInfo.tsx
- src/app/containers/Charts/pow/CFXTransfer.tsx
> feat: update charts style

- src/app/containers/Charts/pos/DailyRewardInfo.tsx
- src/app/containers/Charts/pow/CFXTransfer.tsx
> feat: update style

- src/app/containers/AddressContractDetail/AddressDetailPage.tsx
- src/app/containers/CNS/Loadable.tsx
- src/app/containers/CNS/NotFound.tsx
- src/app/containers/CNS/index.tsx
- src/app/containers/Header/index.tsx
- src/app/index.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
- src/utils/gaConstants.ts
> feat: update cns i18n

- src/app/containers/CNS/index.tsx
> feat: update cns label

- src/app/components/Nav/index.tsx
- src/app/containers/Charts/pow/CirculatingSupply.tsx
- src/app/containers/Charts/pow/TotalSupply.tsx
- src/app/containers/NFTDetail/index.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
- src/utils/constants.ts
- src/utils/hooks/usePlatform.ts
> feat: 1. support transfer in dapp 2. update supply charts

- src/utils/constants.ts
> feat: update max NFT assets list limit value to 10000

- package.json
- yarn.lock
> feat: update cns-util version

- src/app/containers/AddressContractDetail/ContractContent.tsx
> fix: fixed contract verification view null issue

- package.json
- yarn.lock
> feat: update cns-util version to v0.1.25

- package.json
- yarn.lock
Reverts Conflux-Chain/sirius#933
> Revert "feat: update cns-util version to v0.1.25"

- src/app/components/AddressContainer/index.tsx
- src/utils/hooks/useENS.ts
- src/utils/index.ts
- src/utils/tableColumns/account.tsx
- src/utils/tableColumns/block.tsx
- src/utils/tableColumns/contract.tsx
- src/utils/tableColumns/token.tsx
- src/utils/tableColumns/transaction.tsx
> feat: performance optimization

- src/utils/constants.ts
> feat: update NFT list limit value

- src/utils/index.ts
> feat: optimized SDK address related manupulation func

- src/utils/constants.ts
> fix: fixed api host prefix issue

- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
> feat: update Circulating Supply i18n

- src/app/containers/AddressContractDetail/ContractMetadata.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
- src/utils/tableColumns/PendingReason.tsx
> feat: 1. add two pending reason 2. fixed token tracker link issue

- src/app/components/NFTPreview/index.tsx
- src/app/containers/AddressContractDetail/AddressDetailPage.tsx
- src/app/containers/AddressContractDetail/Table.tsx
- src/app/containers/NFTAsset/index.tsx
> feat: optimized

- src/app/containers/AddressContractDetail/AddressMetadata.tsx
- src/app/containers/AddressContractDetail/Table.tsx
> feat: hide useless info by default of account detail page

- src/app/containers/AddressContractDetail/AddressMetadata.tsx
> fix: fixed staking info hide issue

- src/app/containers/Footer/index.tsx
- src/locales/en/translation.json
- src/utils/hooks/useGetTxnStatus.ts
> feat: update developer document link

- src/app/components/Price/Loadable.ts
- src/app/components/Price/index.tsx
- src/app/containers/AddressContractDetail/TokenBalanceSelect.tsx
- src/app/containers/TokenDetail/Basic.tsx
- src/utils/constants.ts
- src/utils/index.ts
- src/utils/tableColumns/token.tsx
> feat: update price format

- src/app/containers/Footer/index.tsx
- src/utils/index.ts
> feat: remove conflux truffle and studio link

- src/app/components/StatsCard/index.tsx
- src/app/containers/Statistics/index.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
> feat: add highest PoW nodes count

- src/app/containers/Approval/Loadable.tsx
- src/app/containers/Approval/NotFound.tsx
- src/app/containers/Approval/index.tsx
- src/app/containers/Header/index.tsx
- src/app/containers/Transaction/Detail.tsx
- src/app/index.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
- src/utils/constants.ts
- src/utils/contract/ERC1155.json
- src/utils/contract/ERC20.json
- src/utils/contract/ERC721.json
- src/utils/gaConstants.ts
- src/utils/hooks/useENSOrAddressSearch.ts
- src/utils/httpRequest.ts
- src/utils/tableColumns/token.tsx
> feat: add approval

- src/app/containers/Approval/index.tsx
> fix: fixed auto connect issue of token approvals

- src/app/containers/Sponsor/index.tsx
- src/utils/httpRequest.ts
> feat: update contract info api of sponsor page

- src/app/containers/NFTDetail/index.tsx
> fix: SCAN-4610

- src/app/containers/AddressContractDetail/Nametag.tsx
- src/utils/hooks/useNametag.ts
> feat: handle incorrect nametag labels issue

- src/app/components/StatsCard/index.tsx
> fix: fixed miners statistic issue

- src/app/components/AddressContainer/index.tsx
- src/app/containers/AddressContractDetail/Nametag.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
- src/locales/zh_cn/translationForDotNet.json
> fix: SCAN-4619, SCAN-4620, SCAN-4621

- src/app/containers/AddressContractDetail/Nametag.tsx
> fix: name tag labels length condition issue

- src/app/components/SponsorStorage/Loadable.ts
- src/app/components/SponsorStorage/index.tsx
- src/app/containers/AddressContractDetail/AddressInfoCards.tsx
- src/app/containers/Sponsor/index.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
- src/utils/api.ts
- src/utils/index.ts
> feat: add sponsor storage info popover

- src/app/components/SponsorStorage/index.tsx
- src/app/containers/AddressContractDetail/AddressInfoCards.tsx
> fix: fixed sponsor storage issue

- src/app/containers/Sponsor/index.tsx
> fix: fixed sponsor storage quota issue of sponsor page

- src/locales/zh_cn/translationForDotNet.json
> fix: fixed typo of storage sponsor in address detail page

- package.json
- src/app/containers/AddressContractDetail/Table.tsx
- yarn.lock
> fix: address transfers display bug

- package.json
> fix: update node version

- src/app/components/Charts/StockChartTemplate.tsx
- src/utils/index.ts
> fix: charts hide animation

- src/app/components/ContractAbi/OutputItem.tsx
- src/utils/index.ts
> fix: parse data in bytes format

- src/app/components/Charts/StockChartTemplate.tsx
- src/app/components/ContractAbi/OutputItem.tsx
- src/utils/index.ts
> Parse data in bytes format

- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
> fix: gasUsed translate

- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
> fix: gasUsed translate again

- src/app/components/AddressContainer/index.tsx
- src/utils/index.ts
> fix: bug caused by parsing byte

- src/utils/constants.ts
> feat: replacement RPC_URL

- src/app/components/Charts/StockChartTemplate.tsx
- src/app/containers/AddressContractDetail/ContractContent.tsx
- src/locales/en/translation.json
- src/locales/zh_cn/translation.json
1.Optimize text
2.Display the internal contract code, abi
3.Optimize the chart
> fix some bugs

- src/app/components/NFTPreview/3D.tsx
- src/app/components/NFTPreview/index.tsx
- src/app/containers/NFTDetail/index.tsx
> fix: 3d render

- src/app/components/NFTPreview/index.tsx
> fix: nftinfo error

- src/app/index.tsx
- src/utils/constants.ts
> feat: api host

- src/app/containers/Header/HeaderLink.tsx
> fix: styled-components error

- src/index.tsx
> fix: react dom render

- config-overrides.js
- package.json
- src/app/containers/NFTDetail/index.tsx
- src/utils/httpRequest.ts
- yarn.lock
> feat: metadata backup

- src/app/components/TablePanelNew/index.tsx
- src/app/containers/pos/Account/IncomingHistory.tsx
- src/app/containers/pos/Account/VotingHistory.tsx
- src/app/containers/pos/Accounts/index.tsx
- src/app/containers/pos/Block/VotingAddress.tsx
- src/app/containers/pos/Blocks/index.tsx
- src/app/containers/pos/Committee/votesDistribution.tsx
- src/app/containers/pos/IncomingRank/Leaderboard.tsx
- src/app/containers/pos/Transactions/index.tsx
> fix: pos table sort

- src/app/index.tsx
> fix: remove loading after fetch

- src/utils/tableColumns/transaction.tsx
> fix: verified logic

- src/app/containers/AddressContractDetail/ContractMetadata.tsx
> fix: addressContainer error

- config-overrides.js
> fix: react-i18next

- src/app/components/NFTPreview/index.tsx
- src/app/components/ProjectInfo/icons.tsx
- src/app/containers/NFTDetail/index.tsx
- src/app/containers/NetworkError/index.tsx
- src/utils/tableColumns/utils.tsx
> fix: tooltip style

- .eslintrc.js
- package.json
- src/utils/index.ts
- yarn.lock
> fix: address type

- src/env/env-constants.ts
- yarn.lock
> fix: mainnet

- src/app/containers/Charts/cip1559Metrics/AveragePriorityFeePerBlock.tsx
- src/app/containers/Charts/cip1559Metrics/GasUsedPerBlock.tsx
- src/app/containers/Charts/cip1559Metrics/PercentageOfTxTypeInBlock.tsx
- yarn.lock
> fix: hidden charts x-axis

- package.json
- yarn.lock
> feat: next version

- src/app/containers/Block/DescriptionPanel.tsx
> fix: hover pivot height

- package.json
- yarn.lock
> fix: update common version

- src/app/containers/Charts/pow/Token.tsx
> fix: default 365 day

- src/app/containers/Transaction/Detail.tsx
> fix: gasCharged

- package.json
- src/app/containers/Transaction/EventLogs/index.tsx
- src/utils/httpRequest.ts
- yarn.lock
> fix: fetchWithCache

- src/app/containers/Transaction/Detail.tsx
> fix: attr tag wrap

- src/app/containers/BlocknumberCalc/index.tsx
> fix: pos current block number

- package.json
- yarn.lock
> feat: update next version

- src/app/containers/Block/DescriptionPanel.tsx
> fix: gasLimit & gasUsed display

- src/app/containers/pos/Account/Overview.tsx
- src/images/status.svg
- src/images/website.svg
> fix: validator detail ui

- src/app/components/TablePanelNew/index.tsx
- src/app/containers/Tokens/index.tsx
> fix: table sort

- package.json
- src/app/containers/AddressContractDetail/AddressMetadata.tsx
- yarn.lock
> feat: update unlocktime i18n

- package.json
- src/app/containers/pos/Account/Overview.tsx
- yarn.lock
> feat: add validator total income

- README.md
> docs: add build & config readme

- src/app/containers/Footer/index.tsx
> fix: update footer link

- package.json
> feat: remove unused scripts

- README.md
- src/env/core/devnet.ts
- src/env/core/mainnet.ts
- src/env/core/testnet.ts
> fix: remove unused config

- package.json
- yarn.lock
> feat: update i18n version

- config.example
> build: update config file

- config.example
> fix: config.example

- src/utils/request.ts
> fix: compatible espace response

- src/app/containers/Transactions/components/AdvancedSearchForm.tsx
> fix: dayjs

- package.json
- yarn.lock
> fix: update use-wallet version

- src/app/index.tsx
> fix: frontend api

- src/app/containers/Charts/cip1559Metrics/AveragePriorityFeePerBlock.tsx
- src/app/containers/Charts/cip1559Metrics/BaseFeePerBlock.tsx
- src/app/containers/Charts/cip1559Metrics/GasUsedPerBlock.tsx
> fix: prettier

- src/app/components/TablePanelNew/index.tsx
> fix: csv download

- package.json
> fix: add build:prod script

- src/app/components/TablePanelNew/index.tsx
- src/app/containers/AddressContractDetail/ContractDetailPage.tsx
- src/app/containers/pos/Account/VotingHistory.tsx
- src/app/containers/pos/Accounts/index.tsx
> fix: refresh table data while table url changed

- src/app/containers/Transaction/Detail.tsx
- src/app/containers/Transaction/index.tsx
- src/utils/api.ts
> fix: duplicate request

- src/app/containers/Transaction/Detail.tsx
- src/utils/tableColumns/utils.tsx
> fix: age render

- src/app/containers/Block/DescriptionPanel.tsx
> fix: 1559 block display

- src/app/containers/pos/Account/RightStatus.tsx
> fix: pending rights status row key

- src/app/containers/Charts/crossSpace/DailyCFXTransfer.tsx
> fix: cross space chart i18n

- src/app/containers/BlocknumberCalc/index.tsx
> fix: clear input

- src/app/containers/BlocknumberCalc/Countdown.tsx
- src/app/containers/BlocknumberCalc/index.tsx
> fix: countdown

- src/app/containers/BlocknumberCalc/index.tsx
> fix: error

- src/app/containers/BlocknumberCalc/Countdown.tsx
> fix: outdate

- src/app/containers/pos/HomePage/BlockchainInfo.tsx
> feat: update base rate

- package.json
- yarn.lock
> fix: i18n typo

- src/app/components/ContractAbi/Func.tsx
> fix: contract input parse

- src/app/containers/Header/HeaderLink.tsx
- src/app/containers/Header/index.tsx
- src/app/index.tsx
- src/utils/constants.ts
- src/utils/hooks/useGlobal.ts
- src/utils/index.ts
> feat: network-switch ui refactor

- package.json
- src/app/containers/Transaction/Detail.tsx
- src/app/containers/Transaction/EventLogs/Address.tsx
- src/app/containers/Transaction/EventLogs/StyledComponents.tsx
- src/app/containers/Transaction/EventLogs/Topics.tsx
- src/styles/global-styles.ts
- src/utils/tableColumns/block.tsx
- src/utils/tableColumns/token.tsx
- src/utils/tableColumns/transaction.tsx
- yarn.lock
> feat: highlight

- package.json
- yarn.lock
> update sirius-next version

- src/app/containers/Blocks/index.tsx
> fix: columns width

- src/env/index.ts
- src/types/global.d.ts
> feat: add window.customConfig

- src/app/components/ContractAbi/Func.tsx
> feat: write contract from param

- package.json
- src/utils/api.ts
- src/utils/hooks/useTableDataByHttp.ts
- yarn.lock
> fix: query-string

- src/app/components/StatsCard/NetworkPie.tsx
- src/app/components/StatsCard/index.tsx
> fix: gas fee unit in network top statistics

- src/app/components/TablePanelNew/index.tsx
- src/app/containers/Transactions/CFXTxns.tsx
- src/app/containers/Transactions/CRC1155Txns.tsx
- src/app/containers/Transactions/CRC20Txns.tsx
- src/app/containers/Transactions/CRC721Txns.tsx
- src/app/containers/Transactions/ExcutedTxns.tsx
- src/utils/tableColumns/token.tsx
> feat: phishing address

- package.json
- yarn.lock
> fix: cns i18n

- package.json
- yarn.lock
> feat: update common version

- src/utils/tableColumns/transaction.tsx
> fix: to column format in txs

- src/app/containers/ABIVerification/index.tsx
- src/utils/tableColumns/transaction.tsx
> fix: columns width & reset txData after submit

- src/app/containers/ABIVerification/index.tsx
> fix: mobile placeholder ui

- package.json
- src/app/containers/AddressContractDetail/ContractContent.tsx
- src/app/containers/ContractVerification/Step1.tsx
- src/app/containers/ContractVerification/Step2.tsx
- src/app/containers/ContractVerification/StyledComponents.ts
- src/app/containers/ContractVerification/constants.ts
- src/app/containers/ContractVerification/index.tsx
- src/images/chevron-left.svg
- src/utils/httpRequest.ts
- yarn.lock
> feat: add vyper contract

- src/app/containers/ContractVerification/Step2.tsx
> fix: file upload error

- src/app/containers/ContractVerification/Step2.tsx
- src/app/containers/ContractVerification/index.tsx
> fix: file upload code format
